#this scenario will be executed in case of pushing a new part of logic to the target branch via PR merge
name: on merge ochestration logic

#depends on the target branch one of the following scenarios will be executed:
on:
  push:
    #target branch is: 
    branches:
      - 'dev**'
      - 'qa**'
      - 'staging**'
      - 'uat**'
      - 'prod**'



jobs:
  logger:
    runs-on: ubuntu-latest
    steps:
      - name: logger
        run: echo $GITHUB_REF_NAME


  #this scenario will be executed if the target branch is DEV
  #this scenario will run "USES" section github actions workflow
  dev_pr_munits:
    if: contains(${{ github.ref.name }}, 'dev')
    uses: ./.github/workflows/merge_deploy_dev.yml


  #this scenario will be executed if the target branch is QA
  #this scenario will run "USES" section github actions workflow
  qa_pr_munits:
    if: contains(${{ github.ref.name }}, 'qa')
    uses: ./.github/workflows/merge_deploy_qa.yml


  #this scenario will be executed if the target branch is STAGING
  #this scenario will run "USES" section github actions workflow
  staging_pr_munits:
    if: contains(${{ github.ref.name }}, 'staging')
    uses: ./.github/workflows/merge_deploy_staging.yml


  #this scenario will be executed if the target branch is UAT
  #this scenario will run "USES" section github actions workflow
  uat_pr_munits:
    if: contains(${{ github.ref.name }}, 'uat')
    uses: ./.github/workflows/merge_deploy_uat.yml


  #this scenario will be executed if the target branch is PROD
  #this scenario will run "USES" section github actions workflow
  prod_pr_munits:
    if: contains(${{ github.ref.name }}, 'prod')
    uses: ./.github/workflows/merge_deploy_prod.yml