name: pr ochestration logic

on:
  push:
    branches:
      - 'dev**'
      - 'qa**'
      - 'staging**'
      - 'uat**'
      - 'prod**'



jobs:
  logger:
    runs-on: ubuntu-latest
    steps:
      - name: logger
        run: echo $GITHUB_REF_NAME

  dev_pr_munits:
    if: contains(github.ref.name, 'dev')
    uses: ./.github/workflows/pr_run_munits_dev.yml

  qa_pr_munits:
    if: contains(github.event.pull_request.base.ref, 'qa')
    uses: ./.github/workflows/pr_run_munits_qa.yml

  staging_pr_munits:
    if: contains(github.event.pull_request.base.ref, 'staging')
    uses: ./.github/workflows/pr_run_munits_staging.yml

  uat_pr_munits:
    if: contains(github.event.pull_request.base.ref, 'uat')
    uses: ./.github/workflows/pr_run_munits_uat.yml

  prod_pr_munits:
    if: contains(github.event.pull_request.base.ref, 'prod')
    uses: ./.github/workflows/pr_run_munits_prod.yml