name: pr ochestration logic
#123

on:
  pull_request:
    branches:
      - 'dev**'
      - 'qa**'
      - 'staging**'
      - 'uat**'
      - 'prod**'
    types: [opened, reopened, synchronize]



jobs:
  dev_pr_munits:
    if: github.event.pull_request.base.ref == 'dev'
    uses: ./.github/workflows/test2.yml

  qa_pr_munits:
    if: github.event.pull_request.base.ref == 'qa'
    uses: ./.github/workflows/test2.yml