name: pr ochestration logic

on:
  pull_request:
    branches:
      - 'dev**'
      - 'qa**'
      - 'staging**'
      - 'uat**'
      - 'prod**'
    types: [opened, reopened, synchronize]



jobs:
  logger:
    steps:
      - name: logger
        run: echo "test"

  dev_pr_munits:
    #if: github.event.pull_request.base.ref == 'dev**'
    if: contains(github.event.pull_request.base.ref, 'dev')
    uses: ./.github/workflows/test2.yml