name: run munit tests before deploy to dev env


#runs whenever a pull request has been created
on:
  pull_request:
    branches:
      - 'dev**'
    types: [opened, reopened, synchronize]




#list of the jobs that can be runned
#depends on the context of an event
#job:dev --- runs whenever a pull request, where target branch is dev, has been created


jobs:
  dev:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'dev'
    #in the env section below variables for mulesoft project pom file for the following sections should be defined:
    #1. build --> plugin (org.mule.tools.maven) --> cloudHubDeployment
    #2. build --> plugin (org.mule.tools.maven) --> cloudHubDeployment --> properties 
    env:
      PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME_GITHUB_SECRET_VALUE }}
      PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD_GITHUB_SECRET_VALUE }}

    steps:
      #This action checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v2

      #This step performs:
      # 1. add new dependencies in cache
      # 2. retrieve existing data from cache
      - name: Checking Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 

      #This step runs munit tests env
      #- name: Build with Maven
        #run:  mvn clean test "-DskipMunitBoolean=false" -s .maven/settings.xml