name: my test
#123121

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME_GITHUB_SECRET_VALUE }}
      PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD_GITHUB_SECRET_VALUE }}
      ENV: DEV
      WORKERS: ${{ vars.WORKERS_GITHUB_VALUE }}
      WORKERS_TYPE: ${{ vars.WORKERS_TYPE_GITHUB_VALUE }}
      OBJECT_STORE_V2: ${{ vars.OBJECT_STORE_V2_GITHUB_VALUE }}
      REGION: ${{ vars.REGION_GITHUB_VALUE }}
#POM <properties>
      prop_01_pom_var: prop_01_pom_var_value
      prop_02_pom_var: prop_02_pom_var_value
      prop_03_pom_var: prop_03_pom_var_value
      prop_04_pom_var: prop_04_pom_var_value
      prop_05_pom_var: prop_05_pom_var_value

    steps:
      - name: test
        run: |
          echo "test"
          echo "test 2"
          echo ${{ vars.WORKERS_GITHUB_VALUE }}
          echo "props test-----------------"
          echo "DEV"
          echo ${{ vars.DEV_PROP_01_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.DEV_PROP_02_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.DEV_PROP_03_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.DEV_PROP_04_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.DEV_PROP_05_POM_VAR_GITHUB_VALUE }}


          echo "QA"
          echo ${{ vars.QA_PROP_01_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.QA_PROP_02_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.QA_PROP_03_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.QA_PROP_04_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.QA_PROP_05_POM_VAR_GITHUB_VALUE }}


          echo "STAGING"
          echo ${{ vars.STAGING_PROP_01_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.STAGING_PROP_02_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.STAGING_PROP_03_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.STAGING_PROP_04_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.STAGING_PROP_05_POM_VAR_GITHUB_VALUE }}


          echo "UAT"
          echo ${{ vars.UAT_PROP_01_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.UAT_PROP_02_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.UAT_PROP_03_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.UAT_PROP_04_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.UAT_PROP_05_POM_VAR_GITHUB_VALUE }}


          echo "PROD"
          echo ${{ vars.PROD_01_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.PROD_01_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.PROD_01_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.PROD_01_POM_VAR_GITHUB_VALUE }}
          echo ${{ vars.PROD_01_POM_VAR_GITHUB_VALUE }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checking Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 

      - name: Build with Maven
        run: echo "test"
        #run: mvn clean -B package -s .maven/settings.xml  -X
        #run:  mvn clean deploy "-DmuleDeploy" "-Denv=dev" -s .maven/settings.xml