name: my test
#123

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLATFORM_USERNAME: artem_Bubnov
      PLATFORM_PASSWORD: zvGF62HVCWpyzsPP

    steps:
      - name: test
        run: |
          echo "test"
          echo "test 2"
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checking Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 

      - name: Build with Maven
        #run: mvn clean -B package -s .maven/settings.xml 
        run:  mvn clean deploy "-DmuleDeploy" -s .maven/settings.xml